import { useCallback, useEffect, useRef, useState } from 'react'
import type { DownloadRequest, MediaInfo } from '@shared/types'
import { useStore } from '../store'
import { Icon, Spinner, Toggle } from '../components/ui'
import { MediaCard } from '../components/MediaCard'
import { FormatPicker, FormatSelection } from '../components/FormatPicker'
import { looksLikeUrl, shortPath } from '../lib/format'

export function Home(): JSX.Element {
  const { settings, updateSettings, setView, handoff, clearHandoffUrl } = useStore()

  const [url, setUrl] = useState('')
  const [analyzing, setAnalyzing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [info, setInfo] = useState<MediaInfo | null>(null)
  const [selection, setSelection] = useState<FormatSelection | null>(null)
  const [saveDir, setSaveDir] = useState('')
  const [wholePlaylist, setWholePlaylist] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [clip, setClip] = useState<string | null>(null)
  const [dismissedClip, setDismissedClip] = useState<string | null>(null)
  const analyzeSequence = useRef(0)

  const [subsEnabled, setSubsEnabled] = useState(false)
  const [subLangs, setSubLangs] = useState<string[]>([])
  const [subEmbed, setSubEmbed] = useState(true)

  useEffect(() => () => {
    analyzeSequence.current += 1
  }, [])

  useEffect(() => {
    if (settings && !saveDir) setSaveDir(settings.defaultSaveDir)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [settings])

  // A link handed off from the browser (snag://) starts analyzing immediately.
  // Keyed on the handoff seq, not the URL, so repeated clicks on the same link
  // each re-fire instead of collapsing on string equality.
  useEffect(() => {
    if (!handoff) return
    clearHandoffUrl()
    void runAnalyze(handoff.url)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [handoff?.seq])

  const checkClipboard = useCallback(async () => {
    try {
      const text = (await window.api.readClipboard()).trim()
      if (looksLikeUrl(text) && text !== url.trim() && text !== dismissedClip) setClip(text)
      else setClip(null)
    } catch {
      /* ignore */
    }
  }, [url, dismissedClip])

  useEffect(() => {
    checkClipboard()
    const onFocus = (): void => {
      checkClipboard()
    }
    window.addEventListener('focus', onFocus)
    return () => window.removeEventListener('focus', onFocus)
  }, [checkClipboard])

  const runAnalyze = async (target?: string): Promise<void> => {
    const u = (target ?? url).trim()
    if (!u) return
    const requestId = ++analyzeSequence.current
    setUrl(u)
    setClip(null)
    setAnalyzing(true)
    setError(null)
    setInfo(null)
    setSelection(null)
    setWholePlaylist(false)
    try {
      const res = await window.api.analyze(u)
      if (requestId !== analyzeSequence.current) return
      if (res.ok && res.info) {
        setInfo(res.info)
        if (settings) {
          const avail = res.info.subtitleLanguages.map((s) => s.code)
          const preset = settings.subtitles.languages.filter((c) => avail.includes(c))
          setSubsEnabled(settings.subtitles.enabled && avail.length > 0)
          setSubLangs(preset.length ? preset : avail.slice(0, 1))
          setSubEmbed(settings.subtitles.embed)
        }
      } else {
        setError(res.error ?? 'Could not read this link.')
      }
    } catch (err) {
      if (requestId === analyzeSequence.current) {
        setError((err as Error).message || 'Could not read this link.')
      }
    } finally {
      if (requestId === analyzeSequence.current) setAnalyzing(false)
    }
  }

  const pasteInput = async (): Promise<void> => {
    const t = (await window.api.readClipboard()).trim()
    if (t) {
      setUrl(t)
      setClip(null)
    }
  }

  const changeFolder = async (): Promise<void> => {
    const dir = await window.api.pickFolder(saveDir)
    if (dir) setSaveDir(dir)
  }

  const toggleSubLang = (code: string): void => {
    setSubLangs((prev) =>
      prev.includes(code) ? prev.filter((c) => c !== code) : [...prev, code]
    )
  }

  const startDownload = async (): Promise<void> => {
    if (!info || !selection || !selection.valid || !saveDir || submitting) return
    const autoGenerated =
      subsEnabled &&
      subLangs.some((c) => info.subtitleLanguages.find((s) => s.code === c)?.isAuto)

    const request: DownloadRequest = {
      url: info.url,
      title: info.title,
      thumbnail: info.thumbnail,
      kind: selection.kind,
      videoFormatId: selection.videoFormatId,
      audioFormatId: selection.audioFormatId,
      mergeContainer: selection.mergeContainer,
      audioLanguage: selection.audioLanguage,
      audioOutputFormat: selection.audioOutputFormat,
      downloadWholePlaylist: wholePlaylist,
      saveDir,
      subtitles:
        subsEnabled && subLangs.length
          ? { enabled: true, languages: subLangs, embed: subEmbed, autoGenerated }
          : undefined,
      selectionLabel: selection.selectionLabel
    }
    setSubmitting(true)
    setError(null)
    try {
      await window.api.enqueue(request)
      if (settings?.rememberLastChoices && settings.lastKind !== selection.kind) {
        // Keep the renderer's settings snapshot in sync with the value persisted
        // by the main process so the very next analysis restores this choice.
        try {
          await updateSettings({ lastKind: selection.kind })
        } catch (err) {
          console.error('Could not refresh the last format choice:', err)
        }
      }
      setInfo(null)
      setUrl('')
      setSelection(null)
      setError(null)
      setView('queue')
    } catch (err) {
      setError((err as Error).message || 'Could not add this download. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  const canDownload = !!info && !!selection?.valid && !!saveDir && !analyzing && !submitting

  return (
    <div className="screen home">
      <header className="screen-head">
        <h1 className="screen-title">Grab a video</h1>
        <p className="screen-desc">
          Paste a link from YouTube, Vimeo, TikTok, X, and 1000+ other sites.
        </p>
      </header>

      <div className="url-bar">
        <span className="url-icon">
          <Icon name="link" size={18} />
        </span>
        <input
          className="url-input"
          placeholder="https://…"
          value={url}
          spellCheck={false}
          autoFocus
          onChange={(e) => setUrl(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !analyzing) void runAnalyze()
          }}
        />
        <button className="btn-ghost paste-btn" onClick={pasteInput} title="Paste from clipboard">
          <Icon name="paste" size={16} /> Paste
        </button>
        <button className="btn-accent analyze-btn" onClick={() => runAnalyze()} disabled={analyzing || !url.trim()}>
          {analyzing ? <Spinner size={16} /> : <Icon name="sparkle" size={16} />}
          {analyzing ? 'Reading…' : 'Analyze'}
        </button>
      </div>

      {clip && (
        <div className="clip-suggest fade-up">
          <Icon name="paste" size={15} />
          <span className="clip-text">Detected a link on your clipboard</span>
          <code className="clip-url">{clip}</code>
          <button className="btn-mini" onClick={() => runAnalyze(clip)}>
            Use it
          </button>
          <button
            className="btn-mini ghost"
            onClick={() => {
              setDismissedClip(clip)
              setClip(null)
            }}
          >
            Dismiss
          </button>
        </div>
      )}

      {error && (
        <div className="error-box fade-up">
          <Icon name="alert" size={18} />
          <span>{error}</span>
        </div>
      )}

      {analyzing && !info && (
        <div className="analyzing-skeleton fade-up">
          <div className="skel-thumb shimmer" />
          <div className="skel-lines">
            <div className="skel-line shimmer" style={{ width: '70%' }} />
            <div className="skel-line shimmer" style={{ width: '40%' }} />
            <div className="skel-line shimmer" style={{ width: '90%', height: 44 }} />
          </div>
        </div>
      )}

      {info && (
        <div className="result">
          <MediaCard info={info} />

          {settings && <FormatPicker info={info} settings={settings} onChange={setSelection} />}

          {info.playlist && (
            <label className="option-row fade-up">
              <div className="option-main">
                <span className="option-title">Download entire playlist</span>
                <span className="option-sub">
                  {info.playlist.count} videos → saved to a “{info.playlist.title ?? 'playlist'}”
                  subfolder
                </span>
              </div>
              <Toggle
                checked={wholePlaylist}
                onChange={setWholePlaylist}
                label="Download entire playlist"
              />
            </label>
          )}

          {info.subtitleLanguages.length > 0 && (
            <div className="subs-block fade-up">
              <label className="option-row bare">
                <div className="option-main">
                  <span className="option-title">
                    <Icon name="subtitle" size={15} /> Subtitles
                  </span>
                  <span className="option-sub">
                    {info.subtitleLanguages.length} language
                    {info.subtitleLanguages.length > 1 ? 's' : ''} available
                  </span>
                </div>
                <Toggle checked={subsEnabled} onChange={setSubsEnabled} label="Download subtitles" />
              </label>
              {subsEnabled && (
                <div className="subs-detail">
                  <div className="sub-lang-chips">
                    {info.subtitleLanguages.map((s) => (
                      <button
                        key={s.code}
                        className={`chip chip-sm ${subLangs.includes(s.code) ? 'active' : ''}`}
                        onClick={() => toggleSubLang(s.code)}
                      >
                        {s.label}
                      </button>
                    ))}
                  </div>
                  {selection?.kind === 'video' && (
                    <label className="inline-toggle">
                      <Toggle
                        checked={subEmbed}
                        onChange={setSubEmbed}
                        label="Embed subtitles into video file"
                      />
                      <span>Embed into video file</span>
                    </label>
                  )}
                </div>
              )}
            </div>
          )}

          <div className="save-row fade-up">
            <button className="folder-pick" onClick={changeFolder}>
              <Icon name="folder" size={17} />
              <div className="folder-info">
                <span className="folder-label">Save to</span>
                <span className="folder-path" title={saveDir}>
                  {shortPath(saveDir, 50)}
                </span>
              </div>
              <span className="folder-change">Change</span>
            </button>

            <button className="btn-accent btn-download" onClick={startDownload} disabled={!canDownload}>
              {submitting ? <Spinner size={17} /> : <Icon name="download" size={18} />}
              <span className="btn-download-label">
                {submitting ? 'Adding…' : 'Download'}
                {selection?.selectionLabel && (
                  <span className="btn-download-sub">{selection.selectionLabel}</span>
                )}
              </span>
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
