import { describe, expect, it } from 'vitest'
import { buildDownloadArgs } from '../src/main/args'
import type { DownloadRequest, Settings } from '../src/shared/types'

const settings: Settings = {
  defaultSaveDir: 'C:\\Downloads',
  speedLimit: { enabled: false, value: 5, unit: 'M' },
  concurrentFragments: 8,
  parallelDownloads: 1,
  filenameTemplate: '%(title)s',
  notificationsEnabled: true,
  subtitles: { enabled: false, languages: ['en'], embed: true, autoGenerated: false },
  preferredVideoContainer: 'mp4',
  preferredAudioFormat: 'mp3',
  rememberLastChoices: true,
  lastKind: 'video',
  ytdlpPath: null,
  embedThumbnail: true,
  embedMetadata: true,
  browserHandoff: 'quick',
  runInBackground: true,
  autoCheckUpdates: true,
  lastUpdateCheck: 0
}

const request: DownloadRequest = {
  url: 'https://example.com/watch/1',
  title: 'Example',
  thumbnail: null,
  kind: 'video',
  videoFormatId: '137',
  audioFormatId: '140',
  mergeContainer: 'mp4',
  saveDir: 'C:\\Downloads',
  selectionLabel: '1080p · MP4'
}

describe('buildDownloadArgs', () => {
  it('uses eight fragments without a rate cap for maximum speed settings', () => {
    const args = buildDownloadArgs(request, settings, { ffmpegLocation: 'C:\\Tools' })
    expect(args).toContain('--concurrent-fragments')
    expect(args[args.indexOf('--concurrent-fragments') + 1]).toBe('8')
    expect(args).not.toContain('--limit-rate')
  })

  it('includes a configured bandwidth cap', () => {
    const args = buildDownloadArgs(
      request,
      { ...settings, speedLimit: { enabled: true, value: 25, unit: 'M' } },
      { ffmpegLocation: null }
    )
    expect(args.slice(args.indexOf('--limit-rate'), args.indexOf('--limit-rate') + 2)).toEqual([
      '--limit-rate',
      '25M'
    ])
  })
})
