import { describe, expect, it, vi } from 'vitest'
import { buildDownloadArgs } from '../src/main/args'
import type { DownloadRequest, Settings } from '../src/shared/types'

vi.mock('electron', () => ({ app: { getPath: () => 'C:\\SnagTest' } }))

import { sanitizeSettings } from '../src/main/settings'

const settings: Settings = sanitizeSettings({
  defaultSaveDir: 'C:\\Downloads',
  speedLimit: { enabled: false, value: 5, unit: 'M' },
  concurrentFragments: 8,
  parallelDownloads: 1,
  filenameTemplate: '%(title)s',
  notificationsEnabled: true,
  subtitles: { enabled: false, languages: ['en'], embed: true, autoGenerated: false },
  preferredVideoContainer: 'mp4',
  preferredAudioFormat: 'mp3',
  rememberLastChoices: true,
  lastKind: 'video',
  ytdlpPath: null,
  embedThumbnail: true,
  embedMetadata: true,
  browserHandoff: 'quick',
  runInBackground: true,
  autoCheckUpdates: true,
  lastUpdateCheck: 0
})

const request: DownloadRequest = {
  url: 'https://example.com/watch/1',
  title: 'Example',
  thumbnail: null,
  kind: 'video',
  videoFormatId: '137',
  audioFormatId: '140',
  mergeContainer: 'mp4',
  saveDir: 'C:\\Downloads',
  selectionLabel: '1080p · MP4'
}

describe('buildDownloadArgs', () => {
  it('routes http and DASH through aria2c with the boost count when the aria2 engine is on', () => {
    const aria = { ...settings, downloadEngine: 'aria2' as const, concurrentFragments: 12 }
    const args = buildDownloadArgs(request, aria, { ffmpegLocation: null, aria2cPath: 'C:/Snag/tools/aria2c.exe' })
    expect(args[args.indexOf('--downloader') + 1]).toBe('http:C:/Snag/tools/aria2c.exe')
    expect(args[args.indexOf('--downloader-args') + 1]).toBe('aria2c:-x12 -s12 -k1M --enable-color=false')
    // Without the executable the setting is inert instead of breaking downloads.
    const fallback = buildDownloadArgs(request, aria, { ffmpegLocation: null, aria2cPath: null })
    expect(fallback).not.toContain('--downloader')
    // The built-in engine never mentions aria2c.
    expect(buildDownloadArgs(request, settings, { ffmpegLocation: null, aria2cPath: 'C:/x/aria2c.exe' })).not.toContain('--downloader')
  })

  it('uses eight fragments without a rate cap for maximum speed settings', () => {
    const args = buildDownloadArgs(request, settings, { ffmpegLocation: 'C:\\Tools' })
    expect(args).toContain('--concurrent-fragments')
    expect(args[args.indexOf('--concurrent-fragments') + 1]).toBe('8')
    expect(args).not.toContain('--limit-rate')
  })

  it('uses Electron as yt-dlp\'s JavaScript runtime', () => {
    const args = buildDownloadArgs(request, settings, {
      ffmpegLocation: null,
      nodeRuntimePath: 'C:\\Program Files\\Snag\\Snag.exe'
    })
    const clearIndex = args.indexOf('--no-js-runtimes')
    expect(clearIndex).toBeGreaterThanOrEqual(0)
    expect(args.slice(clearIndex, clearIndex + 3)).toEqual([
      '--no-js-runtimes',
      '--js-runtimes',
      'node:C:\\Program Files\\Snag\\Snag.exe'
    ])
  })

  it('includes a configured bandwidth cap', () => {
    const args = buildDownloadArgs(
      request,
      { ...settings, speedLimit: { enabled: true, value: 25, unit: 'M' } },
      { ffmpegLocation: null }
    )
    expect(args.slice(args.indexOf('--limit-rate'), args.indexOf('--limit-rate') + 2)).toEqual([
      '--limit-rate',
      '25M'
    ])
  })

  it('remuxes progressive downloads so the chosen container is honored', () => {
    const args = buildDownloadArgs(
      { ...request, audioFormatId: undefined, mergeContainer: 'mkv' },
      settings,
      { ffmpegLocation: null }
    )
    expect(args.slice(args.indexOf('--merge-output-format'), args.indexOf('--merge-output-format') + 2)).toEqual([
      '--merge-output-format',
      'mkv'
    ])
    expect(args.slice(args.indexOf('--remux-video'), args.indexOf('--remux-video') + 2)).toEqual([
      '--remux-video',
      'mkv'
    ])
  })

  it('falls back to WebM-compatible codecs instead of attempting an invalid mux', () => {
    const args = buildDownloadArgs(
      { ...request, mergeContainer: 'webm' },
      settings,
      { ffmpegLocation: null }
    )
    const selector = args[args.indexOf('-f') + 1]
    expect(selector).toContain("137[vcodec~='^(vp8|vp9|vp0?9|av01)']")
    expect(selector).toContain("140[acodec~='^(opus|vorbis)']")
    expect(selector).toContain("bv*[vcodec~='^(vp8|vp9|vp0?9|av01)']+ba[acodec~='^(opus|vorbis)']")
  })

  it('embeds every selected audio language into one video file', () => {
    const args = buildDownloadArgs(
      { ...request, audioFormatIds: ['140-21', '140-0'] },
      { ...settings, embedMetadata: false },
      { ffmpegLocation: null }
    )
    const selector = args[args.indexOf('-f') + 1]
    expect(selector).toContain('137')
    expect(selector).toContain('+140-21')
    expect(selector).toContain('+140-0')
    expect(args).toContain('--audio-multistreams')
    expect(args.filter((arg) => arg === '--embed-metadata')).toHaveLength(1)
    expect(args.slice(args.indexOf('--merge-output-format'), args.indexOf('--merge-output-format') + 2)).toEqual([
      '--merge-output-format',
      'mp4'
    ])
  })
})
