// Shared IPC contract between main and renderer processes.

export type DownloadKind = 'video' | 'audio'
export type VideoContainer = 'mp4' | 'mkv' | 'webm'
export type AudioOutputFormat = 'mp3' | 'm4a' | 'opus' | 'wav' | 'flac' | 'best'

export interface VideoFormat {
  formatId: string
  ext: string
  height: number | null
  width: number | null
  fps: number | null
  vcodec: string
  acodec: string
  tbr: number | null
  vbr: number | null
  filesize: number | null
  filesizeIsApprox: boolean
  formatNote: string
  dynamicRange: string | null
  isProgressive: boolean
  qualityLabel: string
}

export interface AudioFormat {
  formatId: string
  ext: string
  acodec: string
  abr: number | null
  asr: number | null
  audioChannels: number | null
  language: string | null
  languageLabel: string
  formatNote: string
  filesize: number | null
  filesizeIsApprox: boolean
  qualityLabel: string
}

export interface AudioLanguageGroup {
  language: string | null
  languageLabel: string
  isDefault: boolean
  formats: AudioFormat[]
}

export interface SubtitleLang {
  code: string
  label: string
  isAuto: boolean
}

export interface PlaylistInfo {
  title: string | null
  count: number
}

export interface MediaInfo {
  url: string
  id: string
  title: string
  channel: string | null
  uploader: string | null
  durationSeconds: number | null
  durationString: string | null
  thumbnail: string | null
  extractor: string
  isLive: boolean
  videoFormats: VideoFormat[]
  audioGroups: AudioLanguageGroup[]
  hasMultipleAudioLanguages: boolean
  subtitleLanguages: SubtitleLang[]
  playlist: PlaylistInfo | null
}

export interface SubtitleSelection {
  enabled: boolean
  languages: string[]
  embed: boolean
  autoGenerated: boolean
}

export interface DownloadRequest {
  url: string
  title: string
  thumbnail: string | null
  kind: DownloadKind
  // video
  videoFormatId?: string
  audioFormatId?: string
  mergeContainer?: VideoContainer
  // audio-only
  audioLanguage?: string | null
  audioOutputFormat?: AudioOutputFormat
  // playlist
  downloadWholePlaylist?: boolean
  // common
  saveDir: string
  subtitles?: SubtitleSelection
  selectionLabel: string
}

export type JobStatus =
  | 'queued'
  | 'downloading'
  | 'processing'
  | 'completed'
  | 'error'
  | 'canceled'

export interface DownloadJob {
  id: string
  request: DownloadRequest
  status: JobStatus
  progress: number
  speed: string | null
  eta: string | null
  sizeLabel: string | null
  itemLabel: string | null
  filepath: string | null
  errorMessage: string | null
  createdAt: number
  completedAt: number | null
}

export interface ProgressUpdate {
  id: string
  status: JobStatus
  progress: number
  speed: string | null
  eta: string | null
  sizeLabel: string | null
  itemLabel?: string | null
  filepath?: string | null
  errorMessage?: string | null
}

export interface SpeedLimit {
  enabled: boolean
  value: number
  unit: 'K' | 'M'
}

// What a browser handoff (snag:// link) opens: the compact quick dialog or the full app.
export type BrowserHandoff = 'quick' | 'main'

export interface Settings {
  defaultSaveDir: string
  speedLimit: SpeedLimit
  // Parallel connections per download (yt-dlp --concurrent-fragments), 1–16.
  concurrentFragments: number
  parallelDownloads: number
  filenameTemplate: string
  notificationsEnabled: boolean
  subtitles: SubtitleSelection
  preferredVideoContainer: VideoContainer
  preferredAudioFormat: AudioOutputFormat
  rememberLastChoices: boolean
  lastKind: DownloadKind
  ytdlpPath: string | null
  embedThumbnail: boolean
  embedMetadata: boolean
  browserHandoff: BrowserHandoff
  // Keep Snag alive in the tray when all windows close, so downloads continue.
  runInBackground: boolean
  // Look for Snag/yt-dlp updates about once a day.
  autoCheckUpdates: boolean
  // Timestamp of the last automatic update check (internal, not shown in UI).
  lastUpdateCheck: number
}

// What the update check found; null per slot means up to date (or unknown).
export interface UpdateAvailability {
  app: { current: string; latest: string; url: string } | null
  ytdlp: { current: string; latest: string } | null
}

export interface ExtensionInstallResult {
  ok: boolean
  path?: string
  error?: string
}

export interface AnalyzeResult {
  ok: boolean
  info?: MediaInfo
  error?: string
}

export interface ToolStatus {
  ytdlpFound: boolean
  ytdlpPath: string | null
  ytdlpVersion: string | null
  ffmpegFound: boolean
  ffmpegPath: string | null
}

// Bridge exposed on window.api (implemented in preload).
export interface Api {
  analyze: (url: string) => Promise<AnalyzeResult>
  enqueue: (request: DownloadRequest) => Promise<DownloadJob>
  cancel: (jobId: string) => Promise<void>
  retry: (jobId: string) => Promise<DownloadJob | null>
  clearCompleted: () => Promise<void>
  removeJob: (jobId: string) => Promise<void>
  getJobs: () => Promise<DownloadJob[]>
  getSettings: () => Promise<Settings>
  setSettings: (patch: Partial<Settings>) => Promise<Settings>
  pickFolder: (current?: string) => Promise<string | null>
  openPath: (target: string) => Promise<void>
  showInFolder: (target: string) => Promise<void>
  readClipboard: () => Promise<string>
  getToolStatus: () => Promise<ToolStatus>
  updateYtdlp: () => Promise<{ ok: boolean; output: string }>
  onProgress: (cb: (u: ProgressUpdate) => void) => () => void
  onJobAdded: (cb: (j: DownloadJob) => void) => () => void
  // Browser handoff (snag:// deep links)
  consumePendingExternalUrl: () => Promise<string | null>
  onExternalUrl: (cb: (url: string) => void) => () => void
  openInMainWindow: (url: string) => Promise<void>
  installBrowserExtension: () => Promise<ExtensionInstallResult>
  getBrowserExtensionPath: () => Promise<string | null>
  // Updates
  checkForUpdates: () => Promise<UpdateAvailability>
  onUpdateAvailable: (cb: (u: UpdateAvailability) => void) => () => void
}
