// Shared IPC contract between main and renderer processes.

export const DOWNLOAD_KINDS = ['video', 'audio'] as const
export type DownloadKind = (typeof DOWNLOAD_KINDS)[number]

export const VIDEO_CONTAINERS = ['mp4', 'mkv', 'webm'] as const
export type VideoContainer = (typeof VIDEO_CONTAINERS)[number]

export const AUDIO_OUTPUT_FORMATS = ['mp3', 'm4a', 'opus', 'wav', 'flac', 'best'] as const

// Which program fetches the bytes: yt-dlp's own downloader, or the bundled
// aria2c (many connections per file; used for plain http(s) files and DASH
// fragments, never for HLS).
export const DOWNLOAD_ENGINES = ['native', 'aria2'] as const
export type DownloadEngine = (typeof DOWNLOAD_ENGINES)[number]
export type AudioOutputFormat = (typeof AUDIO_OUTPUT_FORMATS)[number]

export interface VideoFormat {
  formatId: string
  ext: string
  height: number | null
  width: number | null
  fps: number | null
  vcodec: string
  acodec: string
  tbr: number | null
  vbr: number | null
  filesize: number | null
  filesizeIsApprox: boolean
  formatNote: string
  dynamicRange: string | null
  isProgressive: boolean
  qualityLabel: string
}

export interface AudioFormat {
  formatId: string
  ext: string
  acodec: string
  abr: number | null
  asr: number | null
  audioChannels: number | null
  language: string | null
  languageLabel: string
  formatNote: string
  filesize: number | null
  filesizeIsApprox: boolean
  qualityLabel: string
}

export interface AudioLanguageGroup {
  language: string | null
  languageLabel: string
  isDefault: boolean
  formats: AudioFormat[]
}

export interface SubtitleLang {
  code: string
  label: string
  isAuto: boolean
}

export interface PlaylistInfo {
  title: string | null
  count: number
}

export interface MediaInfo {
  url: string
  id: string
  title: string
  channel: string | null
  uploader: string | null
  durationSeconds: number | null
  durationString: string | null
  thumbnail: string | null
  extractor: string
  isLive: boolean
  videoFormats: VideoFormat[]
  audioGroups: AudioLanguageGroup[]
  hasMultipleAudioLanguages: boolean
  subtitleLanguages: SubtitleLang[]
  playlist: PlaylistInfo | null
  // A small direct stream the trim editor can play in-app; null when the site
  // only offers manifests or header-bound URLs.
  previewUrl: string | null
  previewHasAudio: boolean
}

// Download only part of a video (seconds). `precise` re-encodes around the
// cut points so the file starts and ends exactly there instead of at the
// nearest keyframes.
export interface DownloadSection {
  start: number
  end: number
  precise: boolean
}

export interface SubtitleSelection {
  enabled: boolean
  languages: string[]
  embed: boolean
  autoGenerated: boolean
}

export interface DownloadRequest {
  url: string
  title: string
  thumbnail: string | null
  kind: DownloadKind
  // video
  videoFormatId?: string
  audioFormatId?: string
  // Two or more audio tracks to embed as switchable streams (primary first).
  // Takes precedence over audioFormatId when present.
  audioFormatIds?: string[]
  mergeContainer?: VideoContainer
  // audio-only
  audioLanguage?: string | null
  audioOutputFormat?: AudioOutputFormat
  // playlist
  downloadWholePlaylist?: boolean
  // trim
  section?: DownloadSection
  // launch the finished file in its default app
  openWhenDone?: boolean
  // hand the finished file to a share target when done (id from Settings;
  // omitted = the first enabled one)
  shareWhenDone?: boolean
  shareTarget?: string
  // common
  saveDir: string
  subtitles?: SubtitleSelection
  selectionLabel: string
}

export type JobStatus =
  | 'queued'
  | 'downloading'
  | 'processing'
  | 'completed'
  | 'error'
  | 'canceled'
  | 'paused'

export interface DownloadJob {
  id: string
  request: DownloadRequest
  status: JobStatus
  progress: number
  speed: string | null
  eta: string | null
  sizeLabel: string | null
  itemLabel: string | null
  // What yt-dlp is doing after the transfer ("Merging video and audio").
  phase?: string | null
  filepath: string | null
  errorMessage: string | null
  createdAt: number
  completedAt: number | null
}

export interface ProgressUpdate {
  id: string
  status: JobStatus
  progress: number
  speed: string | null
  eta: string | null
  sizeLabel: string | null
  itemLabel?: string | null
  phase?: string | null
  filepath?: string | null
  errorMessage?: string | null
  // Batch downloads start with the URL as their title and learn the real one
  // from the finished file.
  title?: string
}

// How a download's speed reads in the queue, the Chrome panel and the corner
// toast. Megabytes by default: it is what a file manager counts in, and the
// size next to it is measured the same way.
export const SPEED_UNITS = ['mb', 'mbit', 'mib', 'both'] as const
export type SpeedUnit = (typeof SPEED_UNITS)[number]

export const SPEED_LIMIT_UNITS = ['K', 'M'] as const

export interface SpeedLimit {
  enabled: boolean
  value: number
  unit: (typeof SPEED_LIMIT_UNITS)[number]
}

// What a browser handoff (snag:// link) opens: the compact quick dialog or the full app.
export const BROWSER_HANDOFFS = ['quick', 'main'] as const
export type BrowserHandoff = (typeof BROWSER_HANDOFFS)[number]

// Preferred spoken languages: when a video carries several audio tracks
// (YouTube dubs), every matching language is embedded as a switchable track.
export interface MultiAudioSettings {
  enabled: boolean
  languages: string[]
}

// Where yt-dlp gets a signed-in session from. 'extension' = Snag's own Chrome
// extension exports the cookies of supported sites; 'firefox' = yt-dlp reads
// Firefox's cookie store; 'file' = a cookies.txt the user exported.
export const COOKIE_SOURCES = ['none', 'extension', 'firefox', 'file'] as const
export type CookieSource = (typeof COOKIE_SOURCES)[number]

export const THEMES = ['system', 'dark', 'light'] as const
export type Theme = (typeof THEMES)[number]

// SponsorBlock segment categories (https://wiki.sponsor.ajay.app/w/Types).
export const SPONSORBLOCK_CATEGORIES = [
  { id: 'sponsor', label: 'Sponsor', hint: 'Paid promotions and ads' },
  { id: 'selfpromo', label: 'Self-promotion', hint: 'Merch, Patreon, own products' },
  { id: 'interaction', label: 'Interaction reminders', hint: '"Like and subscribe"' },
  { id: 'intro', label: 'Intro', hint: 'Intermissions and intro animations' },
  { id: 'outro', label: 'Outro', hint: 'End cards and credits' },
  { id: 'preview', label: 'Preview / recap', hint: 'Teasers for what comes later' },
  { id: 'music_offtopic', label: 'Non-music section', hint: 'Talking in music videos' },
  { id: 'filler', label: 'Filler', hint: 'Tangents and jokes' }
] as const
export type SponsorBlockCategory = (typeof SPONSORBLOCK_CATEGORIES)[number]['id']

// Cut = removed from the file; mark = kept, but a chapter marks it.
export interface SponsorBlockSettings {
  remove: SponsorBlockCategory[]
  mark: SponsorBlockCategory[]
}

export const GLOBAL_SHORTCUT = 'CommandOrControl+Shift+D'

export interface QuickWindowSize {
  width: number
  height: number
}

export interface Settings {
  defaultSaveDir: string
  speedLimit: SpeedLimit
  // Unit the live download speed is shown in (see SPEED_UNITS).
  speedUnit: SpeedUnit
  // Parallel connections per download (yt-dlp --concurrent-fragments), 1–16.
  concurrentFragments: number
  parallelDownloads: number
  filenameTemplate: string
  notificationsEnabled: boolean
  subtitles: SubtitleSelection
  preferredVideoContainer: VideoContainer
  preferredAudioFormat: AudioOutputFormat
  rememberLastChoices: boolean
  lastKind: DownloadKind
  ytdlpPath: string | null
  embedThumbnail: boolean
  embedMetadata: boolean
  browserHandoff: BrowserHandoff
  browserExtensionPromptDismissed: boolean
  browserExtensionLastSeen: number
  // Keep Snag alive in the tray when all windows close, so downloads continue.
  runInBackground: boolean
  // Start with Windows (tray only) so the quick popup opens instantly.
  launchAtLogin: boolean
  // Condensed picker: one best-quality row per container instead of the table.
  bestQualityMode: boolean
  multiAudio: MultiAudioSettings
  // Look for Snag/yt-dlp updates about once a day.
  autoCheckUpdates: boolean
  // Timestamp of the last automatic update check (internal, not shown in UI).
  lastUpdateCheck: number
  // Apply yt-dlp releases by itself instead of prompting.
  autoUpdateYtdlp: boolean
  // Signed-in downloads (see CookieSource).
  cookieSource: CookieSource
  cookiesFile: string | null
  // When the extension last exported cookies (internal).
  cookiesSyncedAt: number
  // Offer links copied anywhere while a Snag window is open.
  watchClipboard: boolean
  // Ctrl+Shift+D: analyze the clipboard link from anywhere.
  globalShortcutEnabled: boolean
  sponsorBlock: SponsorBlockSettings
  theme: Theme
  quickWindowSize: QuickWindowSize | null
  // Remembered "Open when done" choice.
  openWhenDone: boolean
  // Apps offered by the Share buttons, and whether to ask which one each time.
  shareTargets: ShareTarget[]
  shareAsk: boolean
  downloadEngine: DownloadEngine
  player: Player
}

// Apps a finished file can be handed to. The Windows share panel and Telegram
// are built in; custom entries point at any executable that takes a file path.
export const SHARE_TARGET_KINDS = ['windows', 'telegram', 'custom'] as const
export type ShareTargetKind = (typeof SHARE_TARGET_KINDS)[number]

export interface ShareTarget {
  id: string
  kind: ShareTargetKind
  label: string
  // Executable for custom targets; null for the built-in ones.
  path: string | null
  enabled: boolean
}

export const DEFAULT_SHARE_TARGETS: ShareTarget[] = [
  { id: 'telegram', kind: 'telegram', label: 'Telegram', path: null, enabled: true },
  { id: 'windows', kind: 'windows', label: 'Windows share panel', path: null, enabled: true }
]

// What the Share and Play buttons need to know: which targets are actually
// usable on this machine and which player opens files.
export interface ShareInfo {
  // `icon` is a PNG data URL for custom apps (their own file icon); the
  // built-in targets draw their own symbols.
  targets: (ShareTarget & { installed: boolean; icon: string | null })[]
  ask: boolean
  player: string
  vlcFound: boolean
}

// Which program opens finished files: VLC when installed, or whatever
// Windows associates with the file type.
export const PLAYERS = ['vlc', 'system'] as const
export type Player = (typeof PLAYERS)[number]

export interface CookieStatus {
  source: CookieSource
  syncedAt: number
  hasExport: boolean
  cookiesFile: string | null
}

export interface GlobalShortcutStatus {
  accelerator: string
  registered: boolean
}

export type UpdateCheckStatus = 'success' | 'partial' | 'error'

export interface AppUpdateProgress {
  percent: number
  bytesPerSecond: number
  transferred: number
  total: number
}

// What the update check found. A null slot means up to date only when status is
// "success"; partial/error preserve the distinction between current and unknown.
export interface UpdateAvailability {
  status: UpdateCheckStatus
  app: { current: string; latest: string; url: string; notes: string | null } | null
  ytdlp: { current: string; latest: string } | null
  error: string | null
}

export interface ExtensionInstallResult {
  ok: boolean
  // The folder Chrome can open with Load unpacked (always a real, visible path).
  path?: string
  // True when Windows is redirecting Snag's AppData into a packaged app's
  // private folder, so this path differs from the one Snag would normally use.
  redirected?: boolean
  error?: string
}

// Where Snag's per-user data really lives. Normally logical and physical are
// the same folder; they differ when a packaged (MSIX) parent app makes
// Windows redirect this process's AppData and registry writes.
export interface StorageStatus {
  redirected: boolean
  logicalPath: string
  physicalPath: string
  packageFamily: string | null
}

// Tabs of the Settings screen; deep links (extension prompt, sandbox notice)
// name the one they want opened.
export const SETTINGS_SECTIONS = ['general', 'speed', 'files', 'languages', 'browser', 'engine'] as const
export type SettingsSection = (typeof SETTINGS_SECTIONS)[number]

export type BrowserId = 'chrome' | 'edge' | 'brave'

export interface BrowserInfo {
  id: BrowserId
  name: string
  // URL scheme for browser-internal pages (chrome://, edge://, brave://).
  scheme: string
}

export interface ExtensionSetupResult {
  ok: boolean
  path?: string
  redirected?: boolean
  // Browser that was opened for the user; null when none could be found.
  browser: BrowserInfo | null
  // 'store': Chrome fetches the extension from the Web Store on its own and
  // only asks to enable it. 'unpacked': the user completes Load unpacked.
  mode: 'store' | 'unpacked'
  error?: string
}

export interface BrowserExtensionStatus {
  // Heartbeat seen recently enough to count as installed (about a month).
  detected: boolean
  // Heartbeat seen within the last few minutes: the extension is live now.
  live: boolean
  lastSeen: number
  path: string | null
  redirected: boolean
}

export interface AnalyzeResult {
  ok: boolean
  info?: MediaInfo
  error?: string
}

export interface ToolStatus {
  ytdlpFound: boolean
  ytdlpPath: string | null
  ytdlpVersion: string | null
  ffmpegFound: boolean
  ffmpegPath: string | null
  aria2cFound: boolean
  aria2cPath: string | null
}

// Bridge exposed on window.api (implemented in preload).
export interface Api {
  analyze: (url: string) => Promise<AnalyzeResult>
  enqueue: (request: DownloadRequest) => Promise<DownloadJob>
  cancel: (jobId: string) => Promise<void>
  retry: (jobId: string) => Promise<DownloadJob | null>
  clearCompleted: () => Promise<void>
  // Drops finished jobs whose file is no longer on disk; returns their ids.
  syncJobFiles: () => Promise<string[]>
  removeJob: (jobId: string) => Promise<void>
  getJobs: () => Promise<DownloadJob[]>
  getSettings: () => Promise<Settings>
  setSettings: (patch: Partial<Settings>) => Promise<Settings>
  pickFolder: (current?: string) => Promise<string | null>
  openPath: (target: string) => Promise<string>
  showInFolder: (target: string) => Promise<string>
  readClipboard: () => Promise<string>
  getToolStatus: () => Promise<ToolStatus>
  getAppVersion: () => Promise<string>
  updateYtdlp: () => Promise<{ ok: boolean; output: string }>
  pauseJob: (jobId: string) => Promise<void>
  resumeJob: (jobId: string) => Promise<void>
  // Full display order (top to bottom); queued jobs download in that order.
  reorderJobs: (jobIds: string[]) => Promise<void>
  onProgress: (cb: (u: ProgressUpdate) => void) => () => void
  onJobAdded: (cb: (j: DownloadJob) => void) => () => void
  onJobsRemoved: (cb: (ids: string[]) => void) => () => void
  // A link copied anywhere while Snag is open (clipboard watch setting).
  onClipboardUrl: (cb: (url: string) => void) => () => void
  // yt-dlp was updated in the background; refresh the engine status.
  onToolsChanged: (cb: () => void) => () => void
  // Signed-in downloads
  getCookieStatus: () => Promise<CookieStatus>
  pickCookiesFile: () => Promise<string | null>
  forgetCookies: () => Promise<void>
  getGlobalShortcutStatus: () => Promise<GlobalShortcutStatus>
  // Browser handoff (snag:// deep links)
  consumePendingExternalUrl: () => Promise<string | null>
  consumePendingOpenSettings: () => Promise<SettingsSection | null>
  onExternalUrl: (cb: (url: string) => void) => () => void
  onOpenSettings: (cb: (section: SettingsSection) => void) => () => void
  openInMainWindow: (url: string) => Promise<void>
  installBrowserExtension: () => Promise<ExtensionInstallResult>
  getBrowserExtensionPath: () => Promise<string | null>
  getBrowserExtensionStatus: () => Promise<BrowserExtensionStatus>
  // One-button setup: prepares the folder, copies its path, opens the default
  // Chromium browser's extensions page (or registers a Web Store install).
  beginExtensionSetup: () => Promise<ExtensionSetupResult>
  getDefaultBrowser: () => Promise<BrowserInfo | null>
  openBrowserExtensionsPage: () => Promise<string>
  revealBrowserExtensionFolder: () => Promise<string>
  copyText: (text: string) => Promise<void>
  getStorageStatus: () => Promise<StorageStatus>
  relaunchOutsideSandbox: () => Promise<boolean>
  deleteJobFile: (jobId: string) => Promise<{ ok: boolean; error?: string }>
  deleteCompletedFiles: () => Promise<{ deletedIds: string[]; errors: string[] }>
  shareFile: (jobId: string, targetId?: string) => Promise<string>
  getShareInfo: () => Promise<ShareInfo>
  // File dialog for a custom share app (shortcuts are resolved to their
  // program); returns the executable path and a display name.
  pickShareApp: () => Promise<{ path: string; label: string } | null>
  // Opens the finished file in VLC when installed, else the default player.
  playFile: (jobId: string) => Promise<string>
  // Updates
  checkForUpdates: () => Promise<UpdateAvailability>
  dismissUpdates: () => Promise<void>
  onUpdateAvailable: (cb: (u: UpdateAvailability) => void) => () => void
  // In-app update download & install (installed builds only)
  canAutoUpdate: () => Promise<boolean>
  downloadAppUpdate: () => Promise<{ ok: boolean; downloaded?: boolean; error?: string }>
  installAppUpdate: () => Promise<boolean>
  onAppUpdateProgress: (cb: (p: AppUpdateProgress) => void) => () => void
  onAppUpdateDownloaded: (cb: () => void) => () => void
  onAppUpdateError: (cb: (message: string) => void) => () => void
}
