import { join } from 'path'
import type { DownloadRequest, Settings } from '@shared/types'

export const PROGRESS_PREFIX = 'SNAGPROG|'

// Emitted once per progress tick on stdout. Fields are pipe-separated and never
// contain a pipe themselves (percent/speed/eta/size strings + playlist counters).
export const PROGRESS_TEMPLATE =
  `download:${PROGRESS_PREFIX}` +
  '%(progress._percent_str)s|%(progress._speed_str)s|%(progress._eta_str)s|' +
  '%(progress._total_bytes_str)s|%(info.playlist_index)s|%(info.n_entries)s'

export interface BuildContext {
  ffmpegLocation: string | null
}

// Pure: turns a request + settings into the full yt-dlp argument vector
// (everything after the executable name, URL included as the final arg).
export function buildDownloadArgs(
  req: DownloadRequest,
  settings: Settings,
  ctx: BuildContext
): string[] {
  const args: string[] = [
    '--newline',
    '--no-color',
    '--ignore-config',
    '--no-warnings',
    '--progress-template',
    PROGRESS_TEMPLATE
  ]

  if (req.downloadWholePlaylist) args.push('--yes-playlist')
  else args.push('--no-playlist')

  if (ctx.ffmpegLocation) {
    args.push('--ffmpeg-location', ctx.ffmpegLocation)
  }

  if (settings.speedLimit.enabled && settings.speedLimit.value > 0) {
    args.push('--limit-rate', `${settings.speedLimit.value}${settings.speedLimit.unit}`)
  }

  // Parallel per-download connections; big speedup on fast lines since hosts
  // throttle per connection. --limit-rate still caps the combined total.
  const frags = Math.max(1, Math.min(16, Math.round(settings.concurrentFragments || 1)))
  if (frags > 1) {
    args.push('--concurrent-fragments', String(frags))
  }

  // Output template. Whole-playlist downloads go into a per-playlist subfolder.
  const namePart = `${settings.filenameTemplate}.%(ext)s`
  const outTemplate = req.downloadWholePlaylist
    ? join(req.saveDir, '%(playlist_title)s', namePart)
    : join(req.saveDir, namePart)
  args.push('-o', outTemplate)

  if (settings.embedMetadata) args.push('--embed-metadata')

  if (req.kind === 'audio') {
    buildAudioArgs(req, settings, args)
  } else {
    buildVideoArgs(req, settings, args)
  }

  buildSubtitleArgs(req, args)

  args.push(req.url)
  return args
}

function buildVideoArgs(req: DownloadRequest, settings: Settings, args: string[]): void {
  const container = req.mergeContainer || settings.preferredVideoContainer
  let selector: string
  if (req.videoFormatId) {
    selector = req.audioFormatId
      ? `${req.videoFormatId}+${req.audioFormatId}`
      : req.videoFormatId
  } else if (container === 'mp4') {
    // Prefer codecs that actually fit an mp4 container (avc1/av01 + m4a), so the
    // "best" fallback doesn't silently spill into .mkv on VP9-only sources.
    selector = "bv*[vcodec~='^(avc1|av01|h264|hev1|hvc1)']+ba[ext=m4a]/bv*+ba/b"
  } else {
    selector = 'bv*+ba/b'
  }
  args.push('-f', selector)
  args.push('--merge-output-format', container)
}

function buildAudioArgs(req: DownloadRequest, settings: Settings, args: string[]): void {
  const selector = req.audioFormatId || 'bestaudio/best'
  args.push('-f', selector)
  args.push('--extract-audio')
  const fmt = req.audioOutputFormat || settings.preferredAudioFormat
  args.push('--audio-format', fmt)
  args.push('--audio-quality', '0') // best VBR for lossy; ignored for lossless
  if (settings.embedThumbnail) args.push('--embed-thumbnail')
}

function buildSubtitleArgs(req: DownloadRequest, args: string[]): void {
  const subs = req.subtitles
  if (!subs || !subs.enabled || subs.languages.length === 0) return
  args.push('--write-subs')
  if (subs.autoGenerated) args.push('--write-auto-subs')
  args.push('--sub-langs', subs.languages.join(','))
  args.push('--convert-subs', 'srt')
  if (subs.embed && req.kind === 'video') args.push('--embed-subs')
}
