import { app } from 'electron'
import { cpSync, existsSync, renameSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'
import { getLocalApiToken, LOCAL_API_PORTS } from './localApi'
import { getStorageStatus, sandboxedCopies, toPhysicalPath } from './storage'
import type { ExtensionInstallResult } from '@shared/types'

// The extension ships inside the app (extraResources in the packaged build,
// the repo folder in dev). Chrome must load it from a path that survives app
// updates and doesn't point into the install directory, so "installing" means
// copying it into userData and letting the user run Load unpacked on that copy.

const EXTENSION_DIR = 'browser-extension'

function bundledExtensionDir(): string {
  return app.isPackaged
    ? join(process.resourcesPath, 'extension')
    : join(app.getAppPath(), 'extension')
}

function installDir(): string {
  return join(app.getPath('userData'), EXTENSION_DIR)
}

// The folder Chrome can actually open. When Windows redirects this process's
// AppData into a packaged app's private LocalCache, that is where the files
// really are — showing the logical path would send the user to an empty or
// missing folder.
export function getInstalledExtensionPath(): string | null {
  const dir = installDir()
  return existsSync(join(dir, 'manifest.json')) ? toPhysicalPath(getStorageStatus(), dir) : null
}

function writeExtensionCopy(src: string, dest: string): void {
  const staging = `${dest}.staging`
  const backup = `${dest}.backup`
  try {
    // Build a complete replacement first. Copying over the old directory leaves
    // removed scripts behind, which can make an unpacked extension run a mixture
    // of releases.
    rmSync(staging, { recursive: true, force: true })
    rmSync(backup, { recursive: true, force: true })
    cpSync(src, staging, { recursive: true })
    writeFileSync(join(staging, '.snag-version'), app.getVersion(), 'utf8')

    // Pair the copy with this installation: the in-page panel authenticates
    // against Snag's loopback API with this token. Never committed to the
    // repo — the bundled config.js placeholder keeps the deep-link fallback.
    writeFileSync(
      join(staging, 'config.js'),
      `// Generated by Snag ${app.getVersion()} — do not edit or share.\n` +
        `var SNAG_CONFIG = ${JSON.stringify({ token: getLocalApiToken(), ports: LOCAL_API_PORTS })}\n`,
      'utf8'
    )

    if (existsSync(dest)) renameSync(dest, backup)
    try {
      renameSync(staging, dest)
    } catch (err) {
      if (existsSync(backup) && !existsSync(dest)) renameSync(backup, dest)
      throw err
    }
    rmSync(backup, { recursive: true, force: true })
  } catch (err) {
    rmSync(staging, { recursive: true, force: true })
    throw err
  }
}

export function installBrowserExtension(): ExtensionInstallResult {
  const src = bundledExtensionDir()
  if (!existsSync(join(src, 'manifest.json'))) {
    return { ok: false, error: 'The bundled extension files were not found.' }
  }

  const dest = installDir()
  try {
    writeExtensionCopy(src, dest)
  } catch (err) {
    return { ok: false, error: (err as Error).message }
  }
  const storage = getStorageStatus()
  return { ok: true, path: toPhysicalPath(storage, dest), redirected: storage.redirected }
}

// Chrome may have been pointed at a copy that an earlier sandboxed run left
// inside a packaged app's LocalCache. Keep those copies current and paired
// too, so whichever folder Chrome loaded keeps working after app updates.
function refreshSandboxedCopies(): void {
  if (getStorageStatus().redirected) return
  const src = bundledExtensionDir()
  for (const copy of sandboxedCopies(app.getPath('userData'))) {
    const dest = join(copy.path, EXTENSION_DIR)
    if (!existsSync(join(dest, 'manifest.json'))) continue
    try {
      writeExtensionCopy(src, dest)
    } catch (err) {
      console.error(`[snag] Could not refresh the extension copy in ${copy.packageFamily}:`, err)
    }
  }
}

// Prepare the stable folder on first launch and refresh it on every later
// launch. Chrome needs one user-approved Load unpacked action, but never needs
// the user to copy/refresh these files again afterward.
export function refreshInstalledBrowserExtension(): ExtensionInstallResult {
  refreshSandboxedCopies()
  return installBrowserExtension()
}
