import { app } from 'electron'
import { cpSync, existsSync, renameSync, rmSync, writeFileSync } from 'fs'
import { join } from 'path'
import { getLocalApiToken, LOCAL_API_PORTS } from './localApi'
import type { ExtensionInstallResult } from '@shared/types'

// The extension ships inside the app (extraResources in the packaged build,
// the repo folder in dev). Chrome must load it from a path that survives app
// updates and doesn't point into the install directory, so "installing" means
// copying it into userData and letting the user run Load unpacked on that copy.

function bundledExtensionDir(): string {
  return app.isPackaged
    ? join(process.resourcesPath, 'extension')
    : join(app.getAppPath(), 'extension')
}

function installDir(): string {
  return join(app.getPath('userData'), 'browser-extension')
}

export function getInstalledExtensionPath(): string | null {
  const dir = installDir()
  return existsSync(join(dir, 'manifest.json')) ? dir : null
}

export function installBrowserExtension(): ExtensionInstallResult {
  const src = bundledExtensionDir()
  if (!existsSync(join(src, 'manifest.json'))) {
    return { ok: false, error: 'The bundled extension files were not found.' }
  }

  const dest = installDir()
  const staging = `${dest}.staging`
  const backup = `${dest}.backup`
  try {
    // Build a complete replacement first. Copying over the old directory leaves
    // removed scripts behind, which can make an unpacked extension run a mixture
    // of releases.
    rmSync(staging, { recursive: true, force: true })
    rmSync(backup, { recursive: true, force: true })
    cpSync(src, staging, { recursive: true })
    writeFileSync(join(staging, '.snag-version'), app.getVersion(), 'utf8')

    // Pair the copy with this installation: the in-page panel authenticates
    // against Snag's loopback API with this token. Never committed to the
    // repo — the bundled config.js placeholder keeps the deep-link fallback.
    writeFileSync(
      join(staging, 'config.js'),
      `// Generated by Snag ${app.getVersion()} — do not edit or share.\n` +
        `var SNAG_CONFIG = ${JSON.stringify({ token: getLocalApiToken(), ports: LOCAL_API_PORTS })}\n`,
      'utf8'
    )

    if (existsSync(dest)) renameSync(dest, backup)
    try {
      renameSync(staging, dest)
    } catch (err) {
      if (existsSync(backup) && !existsSync(dest)) renameSync(backup, dest)
      throw err
    }
    rmSync(backup, { recursive: true, force: true })
    return { ok: true, path: dest }
  } catch (err) {
    rmSync(staging, { recursive: true, force: true })
    return { ok: false, error: (err as Error).message }
  }
}

// Refresh an already-installed unpacked copy whenever Snag starts. Chrome keeps
// loading the same stable folder; after an app update the user only needs to
// press Reload on chrome://extensions to activate changed extension scripts.
export function refreshInstalledBrowserExtension(): ExtensionInstallResult | null {
  if (!getInstalledExtensionPath()) return null
  return installBrowserExtension()
}
