import { app } from 'electron'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import type { Settings } from '@shared/types'

function defaultSettings(): Settings {
  let downloads: string
  try {
    downloads = app.getPath('downloads')
  } catch {
    downloads = app.getPath('home')
  }
  return {
    defaultSaveDir: downloads,
    speedLimit: { enabled: false, value: 5, unit: 'M' },
    concurrentFragments: 4,
    parallelDownloads: 1,
    filenameTemplate: '%(title)s',
    notificationsEnabled: true,
    subtitles: { enabled: false, languages: ['en'], embed: true, autoGenerated: false },
    preferredVideoContainer: 'mp4',
    preferredAudioFormat: 'mp3',
    rememberLastChoices: true,
    lastKind: 'video',
    ytdlpPath: null,
    embedThumbnail: true,
    embedMetadata: true,
    browserHandoff: 'quick',
    runInBackground: true,
    autoCheckUpdates: true,
    lastUpdateCheck: 0
  }
}

let cache: Settings | null = null

function filePath(): string {
  return join(app.getPath('userData'), 'settings.json')
}

// Deep-ish merge that keeps nested defaults when the stored file predates a field.
function merge(base: Settings, stored: Partial<Settings>): Settings {
  return {
    ...base,
    ...stored,
    speedLimit: { ...base.speedLimit, ...(stored.speedLimit || {}) },
    subtitles: { ...base.subtitles, ...(stored.subtitles || {}) }
  }
}

export function loadSettings(): Settings {
  if (cache) return cache
  const defaults = defaultSettings()
  try {
    const raw = readFileSync(filePath(), 'utf-8')
    cache = merge(defaults, JSON.parse(raw))
  } catch {
    cache = defaults
  }
  return cache
}

export function saveSettings(patch: Partial<Settings>): Settings {
  const current = loadSettings()
  const next = merge(current, patch)
  cache = next
  try {
    const p = filePath()
    if (!existsSync(dirname(p))) mkdirSync(dirname(p), { recursive: true })
    writeFileSync(p, JSON.stringify(next, null, 2), 'utf-8')
  } catch (err) {
    console.error('Failed to persist settings:', err)
  }
  return next
}
